M48
; DRILL file {KiCad 9.0.7} date 2026-02-19T06:16:07+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-19T06:16:07+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X135.65Y-114.6
X161.88Y-121.94
T2
X107.18Y-84.69
X107.18Y-133.69
X165.18Y-84.69
X165.18Y-133.69
M30
